import test from 'node:test';
import assert from 'node:assert/strict';
import {Group,Mesh,BoxGeometry,Vector3} from 'three';
import {createBuildingCollision} from '../src/building-collision.mjs';
import {createClimbing} from '../src/climbing.mjs';
function setup(height=6){const root=new Group(),wall=new Mesh(new BoxGeometry(8,height,2));wall.position.set(0,height/2,-1);root.add(wall);const collision=createBuildingCollision(root),climb=createClimbing({probe:(...args)=>collision.wall(...args),blocked:p=>collision.blocked(p.x,p.z,p.y-1.7),surface:(x,z,y)=>Math.max(0,collision.surface(x,z,y))}),position=new Vector3(0,1.7,.48);return {root,collision,climb,position};}
test('wall probing finds static vertical walls after origin shifts',()=>{const {root,collision}=setup();assert.ok(collision.wall(new Vector3(0,1,.48),new Vector3(0,0,-1)));assert.equal(collision.wall(new Vector3(10,1,.48),new Vector3(0,0,-1)),null);root.position.set(70,5,-140);const hit=collision.wall(new Vector3(70,6,-139.52),new Vector3(0,0,-1));assert.ok(Math.abs(hit.point.z+140)<1e-6);});
test('climbing rises, traverses and mantles onto an unobstructed roof',()=>{const {climb,position}=setup();for(let i=0;i<180;i++)climb.update(.025,{position,yaw:0,forward:1,grounded:position.y<=1.71});assert.ok(position.y>=7.7-1e-5);assert.ok(position.z<0);assert.equal(climb.active,false);});
test('pause preserves attachment and release prevents immediate reattachment',()=>{const {climb,position}=setup(100);for(let i=0;i<40;i++)climb.update(.025,{position,yaw:0,forward:1,grounded:i<6});assert.ok(climb.active);const y=position.y;climb.update(.05,{position,yaw:0,forward:1,paused:true});assert.equal(position.y,y);assert.equal(climb.release(position,true),5);climb.update(.05,{position,yaw:0,forward:1});assert.equal(climb.active,false);});
test('right input traverses right and climbing continues without a stamina limit',()=>{const {climb,position}=setup(100);for(let i=0;i<30;i++)climb.update(.05,{position,yaw:0,forward:1});const x=position.x;climb.update(.05,{position,yaw:0,right:1});assert.ok(position.x>x);for(let i=0;i<400;i++)climb.update(.05,{position,yaw:0,forward:1});assert.ok(climb.active);assert.ok(position.y>40);});
test('an overhead slab blocks ascent rather than teleporting through it',()=>{const {root,position}=setup(6);const ceiling=new Mesh(new BoxGeometry(8,.3,4));ceiling.position.set(0,4,0);root.add(ceiling);const c=createBuildingCollision(root),climb=createClimbing({probe:(...a)=>c.wall(...a),blocked:p=>c.blocked(p.x,p.z,p.y-1.7),surface:(x,z,y)=>Math.max(0,c.surface(x,z,y))});for(let i=0;i<200;i++)climb.update(.025,{position,yaw:0,forward:1});assert.ok(position.y<3.9);});
