import test from 'node:test';
import assert from 'node:assert/strict';
import {Document,NodeIO} from '@gltf-transform/core';
import {validateModel} from '../server/validate.mjs';
export async function triangle(width=8,height=8,depth=8){const d=new Document(),b=d.createBuffer();const p=d.createAccessor().setType('VEC3').setArray(new Float32Array([0,0,0,width,0,0,0,height,depth])).setBuffer(b);d.createScene().addChild(d.createNode().setMesh(d.createMesh().addPrimitive(d.createPrimitive().setAttribute('POSITION',p))));return Buffer.from(await new NodeIO().writeBinary(d));}
test('valid static model has measured world-space bounds',async()=>{const result=await validateModel(await triangle());assert.deepEqual(result.size,[8,8,8]);assert.equal(result.triangles,1);});
test('oversize and corrupt files are rejected',async()=>{await assert.rejects(()=>validateModel(Buffer.from('bad')),/GLB/);await assert.rejects(()=>validateModel(Buffer.alloc(13*1024*1024)),/GLB/);});
test('width and height limits cannot be bypassed',async()=>{const wide=await triangle(65,8),tall=await triangle(8,25);await assert.rejects(()=>validateModel(wide),/尺寸/);await assert.rejects(()=>validateModel(tall),/尺寸/);});
test('nested world transforms count toward the footprint',async()=>{const io=new NodeIO(),d=await io.readBinary(await triangle());d.getRoot().listNodes()[0].setScale([9,1,1]);const bytes=Buffer.from(await io.writeBinary(d));await assert.rejects(()=>validateModel(bytes),/尺寸/);});
function replaceJSON(bytes,edit){const length=bytes.readUInt32LE(12),data=JSON.parse(bytes.subarray(20,20+length));edit(data);const raw=Buffer.from(JSON.stringify(data)),json=Buffer.alloc(Math.ceil(raw.length/4)*4,32);raw.copy(json);const rest=bytes.subarray(20+length),header=Buffer.from(bytes.subarray(0,20));header.writeUInt32LE(20+json.length+rest.length,8);header.writeUInt32LE(json.length,12);return Buffer.concat([header,json,rest]);}
test('external dependencies and animation cannot enter the public world',async()=>{const b=await triangle();await assert.rejects(()=>validateModel(replaceJSON(b,j=>{j.buffers[0].uri='https://example.com/private.bin';})),/外部/);await assert.rejects(()=>validateModel(replaceJSON(b,j=>{j.animations=[{}];})),/静态/);await assert.rejects(()=>validateModel(replaceJSON(b,j=>{j.extensionsUsed=['KHR_lights_punctual'];})),/扩展/);});
test('embedded PNG decodes and oversized textures are refused',async()=>{const sharp=(await import('sharp')).default,io=new NodeIO(),d=await io.readBinary(await triangle()),p=d.getRoot().listMeshes()[0].listPrimitives()[0];p.setAttribute('TEXCOORD_0',d.createAccessor().setType('VEC2').setArray(new Float32Array([0,0,1,0,0,1])).setBuffer(d.getRoot().listBuffers()[0]));const texture=d.createTexture().setMimeType('image/png').setImage(await sharp({create:{width:2,height:2,channels:3,background:'#aabbcc'}}).png().toBuffer());p.setMaterial(d.createMaterial().setBaseColorTexture(texture));await validateModel(Buffer.from(await io.writeBinary(d)));texture.setImage(await sharp({create:{width:2049,height:1,channels:3,background:'#ffffff'}}).png().toBuffer());const bad=Buffer.from(await io.writeBinary(d));await assert.rejects(()=>validateModel(bad),/2048/);});
test('64 metre width and depth accepted, larger depth refused',async()=>{const result=await validateModel(await triangle(64,24,64));assert.deepEqual(result.size,[64,24,64]);const deep=await triangle(8,8,65);await assert.rejects(()=>validateModel(deep),/尺寸/);});
